// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwNv-7iTOHZIR1yXDahiUTFGCMpLzq6mA',
    appId: '1:655315517083:web:5507fca36025280998103e',
    messagingSenderId: '655315517083',
    projectId: 'carrental-ad729',
    authDomain: 'carrental-ad729.firebaseapp.com',
    storageBucket: 'carrental-ad729.firebasestorage.app',
    measurementId: 'G-5FN4C785GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4DbZam4yY6A37P0MHxvjvSxaZejcF-yA',
    appId: '1:655315517083:android:e4c2f2653b9292d198103e',
    messagingSenderId: '655315517083',
    projectId: 'carrental-ad729',
    storageBucket: 'carrental-ad729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ_z4bYCu5U75cYyum2L64D_Y3Gyq_UMU',
    appId: '1:655315517083:ios:3e6cb1090e47137a98103e',
    messagingSenderId: '655315517083',
    projectId: 'carrental-ad729',
    storageBucket: 'carrental-ad729.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ_z4bYCu5U75cYyum2L64D_Y3Gyq_UMU',
    appId: '1:655315517083:ios:3e6cb1090e47137a98103e',
    messagingSenderId: '655315517083',
    projectId: 'carrental-ad729',
    storageBucket: 'carrental-ad729.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwNv-7iTOHZIR1yXDahiUTFGCMpLzq6mA',
    appId: '1:655315517083:web:b46ca7baa32fe02b98103e',
    messagingSenderId: '655315517083',
    projectId: 'carrental-ad729',
    authDomain: 'carrental-ad729.firebaseapp.com',
    storageBucket: 'carrental-ad729.firebasestorage.app',
    measurementId: 'G-WQY7NZ1QR3',
  );
}
